export const PHONE_HREF = "tel:+353871025108"
export const PHONE_DISPLAY = "+353 (0) 87-102-5108"
export const WHATSAPP_URL = "https://wa.me/353871025108"

export type WhatsAppSource =
    | "navbar_desktop"
    | "navbar_mobile"
    | "mobile_menu"
    | "footer_connect"
    | "footer_cta"
    | "main_consultation_cta"
    | "homepage_approach"
    | "contact_page"
    | "conditions_closing_cta"
    | "research_closing_cta"
    | "resources_closing_cta"
    | "science_closing_cta"
    | "self_assessment_closing_cta"
    | "blog_closing_cta"
    | "info_closing_cta"
    | "long_covid_closing_cta"
    | "cork_location_closing_cta"
    | "dublin_location_closing_cta"
    | "ireland_location_closing_cta"
    | "prt_closing_cta"
