import type { Metadata } from "next"
import Breadcrumbs from "@/app/components/Breadcrumbs"
import SeoContentPage from "@/app/components/SeoContentPage"
import { BreadcrumbJsonLd, createPageMetadata } from "@/app/lib/seo"

export const metadata: Metadata = createPageMetadata({
    title: "Pain Reprocessing Therapy in Ireland | Chronic Pain Recovery",
    description:
        "Explore Pain Reprocessing Therapy with Marsha Canny, a chronic pain therapist offering 60-minute online sessions across Ireland and limited in-person sessions in Rochestown, Cork.",
    path: "/treatments/pain-reprocessing-therapy",
})

export default function PainReprocessingTherapyPage() {
    const breadcrumbs = [
        { name: "Home", path: "/" },
        {
            name: "Pain Reprocessing Therapy",
            path: "/treatments/pain-reprocessing-therapy",
        },
    ]

    return (
        <>
            <BreadcrumbJsonLd id="prt-breadcrumb-schema" items={breadcrumbs} />
            <Breadcrumbs items={breadcrumbs} />
            <SeoContentPage
                whatsAppSource="prt_closing_cta"
                hero={{
                    eyebrow: "Retraining pain signals",
                    title: "Pain Reprocessing Therapy in Ireland",
                    intro: "Pain Reprocessing Therapy may help suitable people of all ages with neuroplastic chronic pain by teaching the brain to interpret safe body sensations with less danger. One-to-one support is available online, with limited in-person sessions in Rochestown, Cork.",
                }}
                sections={[
                    {
                        eyebrow: "The method",
                        heading: "What Pain Reprocessing Therapy does",
                        visual: {
                            kind: "illustration",
                            src: "/images/illustrations/pain-neuroscience.png",
                            alt: "",
                        },
                        body: [
                            "Pain Reprocessing Therapy, often called PRT, is based on the idea that some chronic pain is maintained by learned neural pathways rather than ongoing tissue damage. The pain is real, but the danger signal may be inaccurate.",
                            "PRT helps suitable clients observe sensations differently, reduce fear, and build evidence of safety. Over time, this may help the nervous system lower its protective alarm response.",
                        ],
                    },
                    {
                        eyebrow: "What it involves",
                        heading: "Education, safety and somatic tracking",
                        visual: {
                            kind: "illustration",
                            src: "/images/illustrations/mind-body-connection.png",
                            alt: "",
                        },
                        body: [
                            "A central part of PRT is learning why pain can persist after healing and how the brain can misinterpret normal sensations as dangerous. This education can reduce fear and create a foundation for change.",
                            "Somatic tracking is another key practice. It means paying attention to sensations with curiosity and safety rather than alarm, when it is appropriate to do so. This is not about ignoring pain; it is about changing the meaning the brain attaches to it.",
                        ],
                    },
                    {
                        eyebrow: "Who it is for",
                        heading: "When pain may be neuroplastic",
                        visual: {
                            kind: "illustration",
                            src: "/images/illustrations/gradual-recovery.png",
                            alt: "",
                        },
                        body: [
                            "PRT may be relevant when pain began without clear injury, persists beyond expected healing, moves around, varies with stress, improves with distraction, or has not been explained by medical tests.",
                            "It may also be explored alongside symptoms such as fibromyalgia, migraine, back pain, neck pain, IBS, pelvic pain, long covid-related symptoms, and chronic fatigue, as long as medical causes have been assessed.",
                        ],
                    },
                ]}
                listSection={{
                    eyebrow: "Core principles",
                    heading: "How the work supports change",
                    intro: "PRT is not positive thinking. It is a structured way of helping the nervous system update its prediction of danger. One-to-one 60-minute sessions cost €75.",
                    items: [
                        {
                            title: "Pain is real",
                            body: "The starting point is validation. Neuroplastic pain is generated by the brain and nervous system, but it is still a real bodily experience.",
                        },
                        {
                            title: "Pain does not always mean damage",
                            body: "For some chronic pain, the alarm system keeps firing even when tissues are not in ongoing danger.",
                        },
                        {
                            title: "Fear amplifies signals",
                            body: "Fear, avoidance, scanning, and protective tension can reinforce the brain's danger prediction.",
                        },
                        {
                            title: "Safety can be learned",
                            body: "With the right conditions, the brain can learn that certain sensations and movements are safe again.",
                        },
                    ],
                }}
                safetyNote={{
                    heading: "PRT is not for every pain condition",
                    body: "Pain Reprocessing Therapy should only be considered after appropriate medical assessment. It is not a replacement for treatment of active disease, infection, acute injury, cancer, urgent symptoms, or structural problems requiring surgical intervention.",
                }}
                researchLinks={[
                    {
                        title: "The Boulder Chronic Back Pain Study",
                        source: "JAMA Psychiatry, 2022",
                        href: "https://pubmed.ncbi.nlm.nih.gov/34586357/",
                        summary:
                            "Randomised clinical trial of 151 adults with primary chronic back pain comparing PRT with open-label placebo and usual care, with one-year follow-up.",
                    },
                    {
                        title: "Pain Reprocessing Therapy vs Placebo and Usual Care: 5-Year Follow-Up",
                        source: "JAMA Psychiatry, 2025",
                        href: "https://jamanetwork.com/journals/jamapsychiatry/fullarticle/2837160",
                        summary:
                            "Long-term follow-up from the original PRT trial reporting durability of outcomes in chronic back pain. Useful context, while still specific to the trial population studied.",
                    },
                ]}
                relatedLinks={[
                    {
                        href: "/science",
                        label: "The science of chronic pain",
                    },
                    {
                        href: "/blog/pain-reprocessing-therapy-ireland",
                        label: "What is Pain Reprocessing Therapy?",
                    },
                    {
                        href: "/blog/why-pain-persists-after-healing",
                        label: "Why pain persists after healing",
                    },
                ]}
            />
        </>
    )
}
